// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB42gZ_AgxFssL4mjV44MHlWm2xIa7Hs1I',
    appId: '1:476493841388:web:bf4c90f495aec05da7b6c9',
    messagingSenderId: '476493841388',
    projectId: 'blogging-app-2025',
    authDomain: 'blogging-app-2025.firebaseapp.com',
    storageBucket: 'blogging-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKEFTUKH3pNisoiLFwCu9XHgKUvNtQ6l4',
    appId: '1:476493841388:android:74515f7358212550a7b6c9',
    messagingSenderId: '476493841388',
    projectId: 'blogging-app-2025',
    storageBucket: 'blogging-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi4a6e0aSVexv0BZf-QgxOlPUhDGmKjbg',
    appId: '1:476493841388:ios:5211e8d9fe5fa727a7b6c9',
    messagingSenderId: '476493841388',
    projectId: 'blogging-app-2025',
    storageBucket: 'blogging-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.testingProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi4a6e0aSVexv0BZf-QgxOlPUhDGmKjbg',
    appId: '1:476493841388:ios:5211e8d9fe5fa727a7b6c9',
    messagingSenderId: '476493841388',
    projectId: 'blogging-app-2025',
    storageBucket: 'blogging-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.testingProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB42gZ_AgxFssL4mjV44MHlWm2xIa7Hs1I',
    appId: '1:476493841388:web:1fa9cb411ba5fe69a7b6c9',
    messagingSenderId: '476493841388',
    projectId: 'blogging-app-2025',
    authDomain: 'blogging-app-2025.firebaseapp.com',
    storageBucket: 'blogging-app-2025.firebasestorage.app',
  );
}
